version: '2'

services:
  drone-server:
    image: drone/drone:0.8

    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost:9000
      - DRONE_SECRET=testing
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://localhost:3000

  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=localhost:9000
      - DRONE_SECRET=testing


  web:
    image: gitea/gitea:1.3.2
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "22222:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changemelater
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changemelater
    volumes:
      - ./db/:/var/lib/mysql
