version: '3'

services:
  drone-server:
    image: drone/drone:0.8.5
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=false
      - DRONE_HOST=http://drone-server:9000
      - DRONE_SECRET=gitea
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://gitea:3000
      - DRONE_ADMIN=gitea
    labels:
      - "traefik.backend=drone-server"
      - "traefik.frontend.rule=Host:drone-server.docker.localhost"


  drone-agent:
    image: drone/agent:0.8.5
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=gitea
    labels:
      - "traefik.backend=drone-agent"
      - "traefik.frontend.rule=Host:drone-agent.docker.localhost"

  gitea:
    image: gitea/gitea:1.4.1
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "22222:22"
    depends_on:
      - db
    restart: always
    labels:
      - "traefik.backend=gitea"
      - "traefik.frontend.rule=Host:gitea.docker.localhost"

  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
    volumes:
      - ./db/:/var/lib/mysql

  dnsmasq:
    image: andyshinn/dnsmasq:2.75
    ports: 
    - 172.17.0.1:53:53/tcp 
    - 172.17.0.1:53:53/udp 
    cap_add:
    - NET_ADMIN


  traefik:
    image: library/traefik:1.3.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    labels:
      - traefik.frontend.rule=Host:web
      - traefik.port=8080
    networks:
      - proxy
    restart: always 


networks:
  proxy:
    external: true
  internal:
    external: false
