version: '2'

services:
  drone-server:
    image: drone/drone:0.8-alpine

    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=false
      - DRONE_HOST=http://172.30.0.201:9000
      - DRONE_SECRET=gitea
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://172.30.0.200:3000
      - DRONE_ADMIN=gitea


    networks:
      static-network:
        ipv4_address: 172.30.0.201
  drone-agent:
    image: drone/agent:0.8-alpine

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=172.30.0.201:9000
      - DRONE_SECRET=testing


  web:
    image: gitea/gitea:1.3.2
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "22222:22"
    depends_on:
      - db
    restart: always

    networks:
       static-network:
         ipv4_address: 172.30.0.200
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
    volumes:
      - ./db/:/var/lib/mysql




networks:
  static-network:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          ip_range: 172.30.0.0/24

